### ISSUE TITLE
Questions about the onrobot rg2 gripper

### ISSUE THREAD

**Issue by zhanghua7099** [tonydle/ur_onrobot#1]
Hi! Thank you very much for open-sourcing this project! I'm new in onrobot rg2 gripper, and have some questions about the using of it. 

This project provides a method to control the width of the gripper. The gripper's fingertips do not move in parallel, so the different widths will cause the fingertips to move back or forward. This situation may cause the fingertips to poke into the tabletop. 

Could you give me some advice about how to aovid this problem? I want to know the relationship between **fingertip's position** and **gripper width**.

**Comment by tonydle** [comment]
Hi @zhanghua7099! Thanks for checking out the project.

Yes the fingers movement is quite tricky with this gripper. In the [URDF](https://github.com/tonydle/ur_onrobot/blob/main/ur_onrobot_description/urdf/standalone_onrobot_rg2_model_macro.xacro) I added a "gripper_tcp" link that is roughly where the fingers are when they are fully closed. I think you should use it for your planning/collision checking. In the MoveIt config in this project I used that link as the end link.

In the URDF there is also a mimic joint property that maps between the finger_width joint (prismatic joint) and the finger_joint (rotational joint), but note that this is only a rough estimation as the relationship is not actually linear

`
<mimic joint="${prefix}finger_width" multiplier="${0.85 * ((-0.558505 - 0.785398) / 0.110)}" offset="0.785398" />
`

Perhaps you can do something similar for the tcp_joint instead of having it as a fixed joint.

**Comment by zhanghua7099** [comment]
Hi! Thank you very much for answering my question. Currently, I'm testing this gripper rg2 using ur5e. 

However, after I excute the following command based on the readme file:
https://github.com/tonydle/ur_onrobot?tab=readme-ov-file#bringup-when-using-the-tool-io-rs-485-with-e-series-robots

The URCap is set to
https://github.com/tonydle/ur_onrobot/blob/main/images/installation_tool_io.png

However, the gripper can not be launched. What should I do to solve this problem?

Could you please give me some suggestions?

The total log is listed as here. 
```
[ INFO] [1731921234.566474737]: Loaded ur_robot_driver hardware_interface
[ur/ur_tool_communication_bridge-9] process has finished cleanly
log file: /home/zhy/.ros/log/6d46a2ee-a58d-11ef-8211-1bd0dcccd32c/ur-ur_tool_communication_bridge-9*.log
[ INFO] [1731921234.604141261]: waitForService: Service [/ur/controller_manager/switch_controller] is now available.
[ INFO] [1731921234.604160744]: Service available.
[ INFO] [1731921234.604175748]: Waiting for controller list service to come up on /ur/controller_manager/list_controllers
[ INFO] [1731921234.604526342]: Service available.
Traceback (most recent call last):
  File "/home/zhy/ROSProject/ur5e_handeye_ws/devel/lib/ur_onrobot_rg_control/OnRobotRGSerialNode.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 74, in <module>
    OnRobotRGSerial()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 40, in __init__
    self.mainLoop()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 54, in mainLoop
    status = self.gripper.getStatus()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/onrobot/onrobot_rg_control/src/onrobot_rg_control/baseOnRobotRG.py", line 101, in getStatus
    status = self.client.getStatus()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_modbus_serial/src/ur_onrobot_rg_modbus_serial/comModbusSerial.py", line 122, in getStatus
    response = self.client.read_holding_registers(
AttributeError: 'ModbusIOException' object has no attribute 'registers'
[INFO] [1731921234.697824]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1731921234.699179]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1731921234.700434]: Loading controller: joint_state_controller
[INFO] [1731921234.705776]: Loading controller: scaled_pos_joint_traj_controller
[INFO] [1731921234.719668]: Loading controller: speed_scaling_state_controller
[INFO] [1731921234.723742]: Loading controller: force_torque_sensor_controller
[INFO] [1731921234.727871]: Controller Spawner: Loaded controllers: joint_state_controller, scaled_pos_joint_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[INFO] [1731921234.729650]: Started controllers: joint_state_controller, scaled_pos_joint_traj_controller, speed_scaling_state_controller, force_torque_sensor_controller
[INFO] [1731921234.733972]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1731921234.735582]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1731921234.737019]: Loading controller: pos_joint_traj_controller
[INFO] [1731921234.749869]: Loading controller: joint_group_vel_controller
[INFO] [1731921234.753877]: Controller Spawner: Loaded controllers: pos_joint_traj_controller, joint_group_vel_controller
[ INFO] [1731921234.786152948]: Robot mode is now RUNNING
[ INFO] [1731921234.786959930]: Robot's safety mode is now NORMAL
[onrobot/OnRobotRGSerialNode-15] process has died [pid 58894, exit code 1, cmd /home/zhy/ROSProject/ur5e_handeye_ws/devel/lib/ur_onrobot_rg_control/OnRobotRGSerialNode.py __name:=OnRobotRGSerialNode __log:=/home/zhy/.ros/log/6d46a2ee-a58d-11ef-8211-1bd0dcccd32c/onrobot-OnRobotRGSerialNode-15.log].
log file: /home/zhy/.ros/log/6d46a2ee-a58d-11ef-8211-1bd0dcccd32c/onrobot-OnRobotRGSerialNode-15*.log
[onrobot/OnRobotRGSerialNode-15] restarting process
process[onrobot/OnRobotRGSerialNode-15]: started with pid [59178]
Traceback (most recent call last):
  File "/home/zhy/ROSProject/ur5e_handeye_ws/devel/lib/ur_onrobot_rg_control/OnRobotRGSerialNode.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 74, in <module>
    OnRobotRGSerial()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 40, in __init__
    self.mainLoop()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 54, in mainLoop
    status = self.gripper.getStatus()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/onrobot/onrobot_rg_control/src/onrobot_rg_control/baseOnRobotRG.py", line 101, in getStatus
    status = self.client.getStatus()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_modbus_serial/src/ur_onrobot_rg_modbus_serial/comModbusSerial.py", line 122, in getStatus
    response = self.client.read_holding_registers(
  File "/home/zhy/.local/lib/python3.8/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/home/zhy/.local/lib/python3.8/site-packages/pymodbus/client/sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[1000000])]
[onrobot/OnRobotRGSerialNode-15] process has died [pid 59178, exit code 1, cmd /home/zhy/ROSProject/ur5e_handeye_ws/devel/lib/ur_onrobot_rg_control/OnRobotRGSerialNode.py __name:=OnRobotRGSerialNode __log:=/home/zhy/.ros/log/6d46a2ee-a58d-11ef-8211-1bd0dcccd32c/onrobot-OnRobotRGSerialNode-15.log].
log file: /home/zhy/.ros/log/6d46a2ee-a58d-11ef-8211-1bd0dcccd32c/onrobot-OnRobotRGSerialNode-15*.log
[onrobot/OnRobotRGSerialNode-15] restarting process
process[onrobot/OnRobotRGSerialNode-15]: started with pid [59230]
Traceback (most recent call last):
  File "/home/zhy/ROSProject/ur5e_handeye_ws/devel/lib/ur_onrobot_rg_control/OnRobotRGSerialNode.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 74, in <module>
    OnRobotRGSerial()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 40, in __init__
    self.mainLoop()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_control/nodes/OnRobotRGSerialNode.py", line 54, in mainLoop
    status = self.gripper.getStatus()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/onrobot/onrobot_rg_control/src/onrobot_rg_control/baseOnRobotRG.py", line 101, in getStatus
    status = self.client.getStatus()
  File "/home/zhy/ROSProject/ur5e_handeye_ws/src/ur_onrobot/ur_onrobot_rg_modbus_serial/src/ur_onrobot_rg_modbus_serial/comModbusSerial.py", line 122, in getStatus
    response = self.client.read_holding_registers(
  File "/home/zhy/.local/lib/python3.8/site-packages/pymodbus/client/common.py", line 114, in read_holding_registers
    return self.execute(request)
  File "/home/zhy/.local/lib/python3.8/site-packages/pymodbus/client/sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[1000000])]
```

**Comment by tonydle** [comment]
Hi @zhanghua7099 
Do you happen to have the OnRobot URCap installed alongside the RS-485 URCap? In which case in the Installation, make sure to set the OnRobot setting to "No connection"

**Comment by zhanghua7099** [comment]
Yes, the OnRobot URCap was installed alongside the RS-485 URCap. I will try it. Thank you for your help!

**Comment by tonydle** [comment]
No worries! It's exciting that someone outside of our lab is testing this. Please keep me updated ☺️

**Comment by zhanghua7099** [comment]
Hi! @tonydle  

I tried to uninstall the OnRobot URCap and reboot the UR 5e robot. Then, I tried to re-run this project, but the same error still occurred. 

I found this project and it can work:
https://github.com/RyanPaulMcKenna/onRobot
(ps: I didn't know the principle of this project.) 

Thanks again for your kind reply and help!
